/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      // ---- Calviq landing page design tokens (src/calviq) ----
      colors: {
        'surface-container-lowest': '#ffffff',
        outline: '#777587',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714e',
        'inverse-on-surface': '#ecf1ff',
        'secondary-fixed': '#85f8c4',
        'on-tertiary-fixed-variant': '#7b2f00',
        'secondary-container': '#82f5c1',
        'tertiary-fixed': '#ffdbcc',
        'on-tertiary-fixed': '#351000',
        'on-primary-fixed-variant': '#3323cc',
        surface: '#f9f9ff',
        background: '#f9f9ff',
        'on-surface-variant': '#464555',
        'tertiary-fixed-dim': '#ffb695',
        'ai-purple': '#7C3AED',
        'surface-tint': '#4d44e3',
        'outline-variant': '#c7c4d8',
        'alert-amber': '#F59E0B',
        'surface-variant': '#d8e3fb',
        'surface-bright': '#f9f9ff',
        'primary-fixed-dim': '#c3c0ff',
        'error-container': '#ffdad6',
        'surface-container-highest': '#d8e3fb',
        'background-alt': '#F8FAFC',
        'surface-container': '#e7eeff',
        'on-surface': '#111c2d',
        'on-primary-fixed': '#0f0069',
        tertiary: '#7e3000',
        'primary-fixed': '#e2dfff',
        'on-secondary-fixed': '#002114',
        'on-primary-container': '#dad7ff',
        'surface-container-low': '#f0f3ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'primary-container': '#4f46e5',
        'muted-text': '#64748B',
        'dark-gradient-end': '#1E1B4B',
        primary: '#3525cd',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#68dba9',
        'inverse-surface': '#263143',
        'on-tertiary-container': '#ffd2be',
        'tech-teal': '#0891B2',
        'dark-base': '#0F172A',
        'tertiary-container': '#a44100',
        'surface-container-high': '#dee8ff',
        'inverse-primary': '#c3c0ff',
        border: '#E2E8F0',
        'surface-dim': '#cfdaf2',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        secondary: '#006c4a',
        'on-secondary-fixed-variant': '#005137',
        'on-background': '#111c2d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-sm': '8px',
        gutter: '24px',
        'container-max': '1280px',
        'stack-md': '16px',
        'section-gap': '100px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Manrope'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Manrope'],
        'display-lg-mobile': ['Manrope'],
        'display-lg': ['Manrope'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

