/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      // ---- Calviq landing page design tokens (src/calviq) ----
      colors: {
        'surface-container-lowest': '#ffffff',
        outline: '#777587',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714e',
        'inverse-on-surface': '#ecf1ff',
        'secondary-fixed': '#85f8c4',
        'on-tertiary-fixed-variant': '#7b2f00',
        'secondary-container': '#82f5c1',
        'tertiary-fixed': '#ffdbcc',
        'on-tertiary-fixed': '#351000',
        'on-primary-fixed-variant': '#3323cc',
        surface: '#f9f9ff',
        background: '#f9f9ff',
        'on-surface-variant': '#464555',
        'tertiary-fixed-dim': '#ffb695',
        'ai-purple': '#7C3AED',
        'surface-tint': '#4d44e3',
        'outline-variant': '#c7c4d8',
        'alert-amber': '#F59E0B',
        'surface-variant': '#d8e3fb',
        'surface-bright': '#f9f9ff',
        'primary-fixed-dim': '#c3c0ff',
        'error-container': '#ffdad6',
        'surface-container-highest': '#d8e3fb',
        'background-alt': '#F8FAFC',
        'surface-container': '#e7eeff',
        'on-surface': '#111c2d',
        'on-primary-fixed': '#0f0069',
        tertiary: '#7e3000',
        'primary-fixed': '#e2dfff',
        'on-secondary-fixed': '#002114',
        'on-primary-container': '#dad7ff',
        'surface-container-low': '#f0f3ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'primary-container': '#4f46e5',
        'muted-text': '#64748B',
        'dark-gradient-end': '#1E1B4B',
        primary: '#3525cd',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#68dba9',
        'inverse-surface': '#263143',
        'on-tertiary-container': '#ffd2be',
        'tech-teal': '#0891B2',
        'dark-base': '#0F172A',
        'tertiary-container': '#a44100',
        'surface-container-high': '#dee8ff',
        'inverse-primary': '#c3c0ff',
        border: '#E2E8F0',
        'surface-dim': '#cfdaf2',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        secondary: '#006c4a',
        'on-secondary-fixed-variant': '#005137',
        'on-background': '#111c2d',

        // ---- StockLyte landing page design tokens (src/stocklyte) ----
        // Prefixed with "stocklyte-" because this sub-app uses the same
        // Material Design 3 token names as Calviq above (primary, surface,
        // on-surface, etc.) with completely different color values — without
        // the prefix, merging them would silently overwrite Calviq's colors.
        'stocklyte-surface-container-low': '#181c21',
        'stocklyte-on-primary-container': '#00285d',
        'stocklyte-tertiary': '#ffb95f',
        'stocklyte-on-secondary-container': '#00311f',
        'stocklyte-on-secondary-fixed-variant': '#005236',
        'stocklyte-secondary': '#4edea3',
        'stocklyte-on-secondary': '#003824',
        'stocklyte-on-secondary-fixed': '#002113',
        'stocklyte-on-primary-fixed': '#001a42',
        'stocklyte-on-tertiary': '#472a00',
        'stocklyte-secondary-fixed': '#6ffbbe',
        'stocklyte-surface-tint': '#adc6ff',
        'stocklyte-primary-fixed': '#d8e2ff',
        'stocklyte-secondary-container': '#00a572',
        'stocklyte-on-error-container': '#ffdad6',
        'stocklyte-surface-container-highest': '#31353b',
        'stocklyte-on-primary': '#002e6a',
        'stocklyte-surface-variant': '#31353b',
        'stocklyte-outline-variant': '#424754',
        'stocklyte-on-error': '#690005',
        'stocklyte-error-container': '#93000a',
        'stocklyte-surface': '#101419',
        'stocklyte-on-tertiary-fixed': '#2a1700',
        'stocklyte-surface-bright': '#36393f',
        'stocklyte-surface-container': '#1c2025',
        'stocklyte-primary-container': '#4d8eff',
        'stocklyte-on-background': '#e0e2ea',
        'stocklyte-surface-dim': '#101419',
        'stocklyte-tertiary-fixed': '#ffddb8',
        'stocklyte-surface-container-high': '#262a30',
        'stocklyte-secondary-fixed-dim': '#4edea3',
        'stocklyte-on-tertiary-container': '#3e2400',
        'stocklyte-surface-container-lowest': '#0a0e13',
        'stocklyte-outline': '#8c909f',
        'stocklyte-tertiary-container': '#ca8100',
        'stocklyte-on-tertiary-fixed-variant': '#653e00',
        'stocklyte-on-surface-variant': '#c2c6d6',
        'stocklyte-error': '#ffb4ab',
        'stocklyte-on-primary-fixed-variant': '#004395',
        'stocklyte-primary-fixed-dim': '#adc6ff',
        'stocklyte-inverse-on-surface': '#2d3136',
        'stocklyte-inverse-primary': '#005ac2',
        'stocklyte-inverse-surface': '#e0e2ea',
        'stocklyte-on-surface': '#e0e2ea',
        'stocklyte-primary': '#adc6ff',
        'stocklyte-background': '#101419',
        'stocklyte-tertiary-fixed-dim': '#ffb95f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-sm': '8px',
        gutter: '24px',
        'container-max': '1280px',
        'stack-md': '16px',
        'section-gap': '100px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Manrope'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Manrope'],
        'display-lg-mobile': ['Manrope'],
        'display-lg': ['Manrope'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        // ---- StockLyte fonts ----
        'stocklyte-data': ['JetBrains Mono', 'monospace'],
        'stocklyte-headline': ['Space Grotesk', 'sans-serif'],
        'stocklyte-body': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

